version: "3.8"

services:
    laravel:
        image: bitnami/laravel:latest
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        volumes:
            - ./:/app
        depends_on:
            - mysql
        command : ["sh", "-c", "composer install && php artisan key:generate && php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0"]

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        env_file:
            - ./.env
        volumes:
            - mysql-data:/var/lib/mysql

    adminer:
        image: adminer:latest
        depends_on:
            - mysql
        ports:
            - "8080:8080"

volumes:
    mysql-data:
